# 자료형

In [1]:
a = 1; print(type(a))

<class 'int'>


In [4]:
a = 1; a= float(a); print(type(a))
print(a)

<class 'float'>
1.0


In [5]:
a = 1.2; a = int(a); print(type(a))
print(a)

<class 'int'>
1


In [6]:
a = '123'; print(type(a)); print(a[1])

<class 'str'>
2


# 리스트 자료형
>[]로 감싸주고, 요소값을 쉼표로 구분함

In [8]:
a = '123'; a = list(a); print(type(a)); print(a); print(a[2])

<class 'list'>
['1', '2', '3']
3


In [9]:
a = [1,'2',[3,'4']]; print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'list'>
1
2
[3, '4']


# 튜플 자료형
> 리스트와 다르게 ()로 둘러쌈
>
>값의 생성, 삭제, 수정이 불가능 하다는 것이 차이점

In [10]:
a = (1,'2', [3,'4']); print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'tuple'>
1
2
[3, '4']


# 딕셔너리 자료형
>대응형 자료형
>
>딕셔너리 변수명[key] = value 값을 찾을 수 있음. 

In [11]:
a = {"a":"apple", "b":"orange", "c":2014}
print(type(a))
print(a["a"])

<class 'dict'>
apple


In [12]:
a = [(1,2,3), (3,8,0)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

# np.array 
>리스트를 다차원배열로 변경해준다
>
>배열간의 곱은 각 요소들의 곱
# np.matrix
>리스트를 행렬로 변경해준다
>
>2 * 3 행렬끼리의 곱이 불가능하기 때문에 c * T로 행렬의 모양을 바꿔서 곱해준다

In [14]:
import numpy as np
b = np.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


In [15]:
print(b*b)

[[ 1  4  9]
 [ 9 64  0]]


In [16]:
c = np.matrix(b)
print(c)
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


In [17]:
c*c

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [18]:
c*c.T

matrix([[14, 19],
        [19, 73]])