변수
=========
파이썬의 자료형
----------
>숫자형
 * 정수 int(integer)
 * 실수 float(floating point number)
 
>문자열 자료형
 * 문자열 string

파이썬에서 = 는 equal의 의미가 아니라, assign의 의미

class의 의미는? 객체지향을 통해서 만들어지는 것. 항상 같은 변수를 동반하는 함수.

In [17]:
a = 1; print(type(a))

<class 'int'>


**float(a)는 a를 1.0으로 리턴하며, 실수로 읽히기 때문에 print(type(a))는 float**

In [18]:
a = 1; a = float(a); print(type(a))

<class 'float'>


In [19]:
a = 1.2; a = int(a); print(type(a))

<class 'int'>


문자열임을 나타내기 위해서 작은따옴표 ''또는 큰따옴표 "" 를 사용한다. 
문자열 인덱싱
------------
>문자열의 첫번째 자리는 0,1,...
(파이썬은 0부터 숫자를 센다.)

>[-1] 뒤에서부터 읽기 위해서 사용

In [20]:
a = '123'; print(type(a)); print(a[1])

<class 'str'>
2


리스트 자료형
-----------
>list = [element1, element2, element3, ... ]

In [21]:
a = '123'; a = list(a); print(type(a)); print(a); print(a[2])

<class 'list'>
['1', '2', '3']
3


In [22]:
a = [1,'2', [3, '4']]; print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'list'>
1
2
[3, '4']


튜플 자료형
-----------
>리스트와 달리, []가 아닌, ()로 둘러싼다. 리스트는 값을 변경할 수 있지만, 튜플은 수정할 수 없다. 

In [23]:
a = (1,'2', [3, '4']); print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'tuple'>
1
2
[3, '4']


딕셔너리 자료형
---------------
>리스트나 튜플처럼 순차적으로 해당 요소 값을 구하지않고, key를 통해 value를 얻는다. 

>{Key1:Value1, Key2:Value2, Key3:Value3, ...}

>인덱스가 아니라 표제어로 접근하는 점이 리스트와 다르다. 

In [24]:
a =	{"a": "apple", "b": "orange", "c": 2014}
print(type(a))
print(a["a"])

<class 'dict'>
apple


numpy
--------
* 리스트안에 내용이 튜플로 들어있음. 타입은 리스트가 나오지만, 튜플 형식으로 숫자를 구성할 수 있다. -> 행렬과 형태만 비슷 (2x3 matrix)

* python에서 행렬처리가 안 됨 -> 행렬처리할 수 있게하는 numpy를 불러와야 함. 내장함수만으로 부족하기 때문에 import를 쓴다. 필요할 때마다 메모리를 패키지에 올려놓고 쓴다 

* import; 하드디스크에 다운받아 놓은 함수를 메모리로 불러올 때 사용

* import numpy as np : 메모리에 올려놓고, 그 폴더(numpy)에 있는 function array를 쓰자 라고 접근해야하기 때문에 np라고 축약

In [27]:
a=[(1,2,3), (3,8,0)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

* b의 array화. 
* 위에 있는 리스트 내의 튜플과는 달리, 행렬 타입으로 바뀌었다. 
* n dimensional array 

In [28]:
import numpy as np
b = np.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


* 2x3 행렬이 만들어졌다. 2x3 와 2x3 이 곱하면 계산이 안됨. 3x? 형태의 matrix만 곱해질 수 있음. 
* 제곱의 형태로 계산되는 bxb

In [29]:
print(b*b)

[[ 1  4  9]
 [ 9 64  0]]


* array는 행렬이 아니다. np.matrix가 진짜 행렬
-> c x c 는 에러가 나온다. 

In [30]:
c = np.matrix(b)
print(c)
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


In [31]:
c*c

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

* c.T transpose 되어서, 2x3이 3x2 행렬이 되어 곱해질 수 있다. 

In [32]:
c*c.T

matrix([[14, 19],
        [19, 73]])